version: '3.8'

services:
  # Senin mevcut yapay zeka motorun
  ollama-service:
    image: ollama/ollama:latest
    container_name: sozlesme_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  # YENİ EKLENEN: Python FastAPI Servisimiz
  backend-api:
    build: 
      context: ./Backend_API  # Dockerfile'ın bulunduğu klasör yolu
    container_name: sozlesme_api
    ports:
      - "8000:8000"
    environment:
      # API, "localhost" yerine doğrudan Docker ağındaki "ollama-service" ismine bağlanır
      - OLLAMA_BASE_URL=http://ollama-service:11434/v1
    depends_on:
      - ollama-service

volumes:
  ollama_data: