version: '3.8'

services:
#yapay zeka motoru
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    #kalıcı hafıza
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  #streamlit ve rag kodlarının çalışacağı alanı tanımlar
  app:
    #bulunduğun klosördeki dockerfile isimli kısıma bakıp sıfırdan inşa eder
    build: .
    container_name: rag-app-service
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434  # Konteyner içi ortak ağ bağlantısı
    volumes:
      - ./data:/app/data  # LanceDB vektör tabanı ve sözleşmeleri yerelde saklamak için
    depends_on:
      - ollama
    restart: unless-stopped

#yapay zeka moddelerinin saklanaxağı sanal diski kayıt altın alma oluşturma
volumes:
  ollama_data: